name: CICD Pipeline

on: [push]

jobs:
    test: 
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout repo
              uses: actions/checkout@v3
        
            - name: Install Node js
              uses: action/setup-node/@v4
              with: 
                node-version: "22"

            - name: Install packages
              run: npm install

            - name: Test the application
              run: npm run check
